import { DishItem, Table, Order, Booking, StaffProfile, RetailProduct } from './types';

export const STAFF_PROFILE: StaffProfile = {
  name: 'Jessica Harrison',
  role: 'Store Manager & Cashier',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
  ordersServedToday: 42,
  tipsEarned: 120.0,
};

// Packaged Meats Retail Catalog - All ₱88 Pesos Flat Variety Store
export const INITIAL_RETAIL_MEATS: RetailProduct[] = [
  {
    id: 'meat-1',
    sku: 'PM-B001',
    name: 'Thin Sliced Pork Samgyupsal',
    category: 'Pork',
    price: 88.0,
    costPrice: 62.0,
    weight: '500g Frozen Pack',
    stock: 45,
    lowStockThreshold: 10,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800',
    description: 'Premium thin-sliced unmarinated pork belly for grill or pan fry. Standard ₱88 pack.',
    barcode: '480651234001',
  },
  {
    id: 'meat-2',
    sku: 'PM-B002',
    name: 'USDA Choice Beef Samgyup Slices',
    category: 'Beef',
    price: 88.0,
    costPrice: 65.0,
    weight: '400g Frozen Pack',
    stock: 28,
    lowStockThreshold: 8,
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&q=80&w=800',
    description: 'Tender marble-cut beef brisket slices, ideal for Korean BBQ and hotpot.',
    barcode: '480651234002',
  },
  {
    id: 'meat-3',
    sku: 'PM-M001',
    name: 'Sweet Soy Marinated Pork Bulpogi',
    category: 'Marinated BBQ',
    price: 88.0,
    costPrice: 58.0,
    weight: '500g Packaged',
    stock: 18,
    lowStockThreshold: 5,
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&q=80&w=800',
    description: 'Marinated pork slices in authentic sweet soy sauce, sesame seeds, and spring onion blend.',
    barcode: '480651234003',
  },
  {
    id: 'meat-4',
    sku: 'PM-M002',
    name: 'Spicy Gochujang Beef Slices',
    category: 'Marinated BBQ',
    price: 88.0,
    costPrice: 64.0,
    weight: '450g Packaged',
    stock: 7, // Low stock sample!
    lowStockThreshold: 10,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800',
    description: 'Flavorful Korean spicy gochujang chili marinated beef brisket strips.',
    barcode: '480651234004',
  },
  {
    id: 'meat-5',
    sku: 'PM-C001',
    name: 'Boneless Chicken Wings Cut',
    category: 'Chicken',
    price: 88.0,
    costPrice: 50.0,
    weight: '600g Vacuum Pack',
    stock: 35,
    lowStockThreshold: 12,
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&q=80&w=800',
    description: 'Fresh skin-on boneless chicken wing drumettes and mid-wings.',
    barcode: '480651234005',
  },
  {
    id: 'meat-6',
    sku: 'PM-D001',
    name: 'Garlic Hungarian Smoked Sausage',
    category: 'Deli & Sausages',
    price: 88.0,
    costPrice: 55.0,
    weight: '400g Pack (4 pcs)',
    stock: 22,
    lowStockThreshold: 8,
    image: 'https://images.unsplash.com/photo-1585325701165-351af916e581?auto=format&fit=crop&q=80&w=800',
    description: 'Savory wood-smoked Hungarian sausage links infused with roasted garlic and paprika.',
    barcode: '480651234006',
  },
  {
    id: 'meat-7',
    sku: 'PM-P002',
    name: 'Thick Cut Pork Chops Pack',
    category: 'Pork',
    price: 88.0,
    costPrice: 60.0,
    weight: '500g Pack (3 cuts)',
    stock: 14,
    lowStockThreshold: 5,
    image: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?auto=format&fit=crop&q=80&w=800',
    description: 'Juicy center-cut bone-in pork chops, flash frozen to lock in farm freshness.',
    barcode: '480651234007',
  },
  {
    id: 'meat-8',
    sku: 'PM-S001',
    name: 'Tempura Shrimp & Squid Ring Mix',
    category: 'Seafood Packs',
    price: 88.0,
    costPrice: 66.0,
    weight: '350g Frozen Pack',
    stock: 12,
    lowStockThreshold: 6,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=800',
    description: 'Selected squid rings and peeled prawns, clean-cut and ocean frozen.',
    barcode: '480651234008',
  },
];

// Restaurant Dishes Catalog
export const INITIAL_DISHES: DishItem[] = [
  {
    id: 'dish-1',
    name: 'Sunrise Mediterranean Bowl',
    category: 'Bowls',
    price: 88.0,
    weight: '300 g',
    calories: '540 kcal',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=800',
    popular: true,
    description: 'A vibrant medley of grilled chicken, roasted vegetables, and herbed couscous, garnished with feta cheese.',
    additions: [
      { id: 'add-1', name: 'Bell Pepper', price: 15.0 },
      { id: 'add-2', name: 'Steamed Rice', price: 20.0 },
      { id: 'add-3', name: 'Royal Shrimps', price: 35.0 },
    ],
  },
  {
    id: 'dish-2',
    name: 'Fresh Salad with pine nuts',
    category: 'Lunch',
    price: 88.0,
    weight: '230 g',
    calories: '320 kcal',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800',
    popular: true,
    description: 'Crisp baby spinach, cherry tomatoes, cucumbers, toasted pine nuts, and aged balsamic glaze.',
    additions: [
      { id: 'add-5', name: 'Avocado Slice', price: 20.0 },
      { id: 'add-6', name: 'Grilled Halloumi', price: 25.0 },
    ],
  },
  {
    id: 'dish-3',
    name: 'Pumpkin Cream Soup',
    category: 'Soups',
    price: 88.0,
    weight: '180 g',
    calories: '280 kcal',
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&q=80&w=800',
    popular: true,
    description: 'Velvety roasted pumpkin and nutmeg soup topped with toasted pumpkin seeds and heavy cream drizzle.',
    additions: [
      { id: 'add-7', name: 'Garlic Croutons', price: 10.0 },
    ],
  },
  {
    id: 'dish-4',
    name: 'Classic Burger with Cheese and Homemade Sause',
    category: 'Burgers',
    price: 88.0,
    weight: '450 g',
    calories: '720 kcal',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800',
    popular: true,
    description: 'Prime Angus beef patty, melted sharp cheddar, caramelized onions, crisp lettuce, tomato, and chef burger sauce.',
    additions: [
      { id: 'add-9', name: 'Extra Crispy Bacon', price: 25.0 },
      { id: 'add-10', name: 'Double Cheese', price: 15.0 },
    ],
  },
  {
    id: 'dish-5',
    name: 'Salmon Poke Bowl with Avocado & Fresh Veggies',
    category: 'Lunch',
    price: 88.0,
    weight: '340 g',
    calories: '610 kcal',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800',
    popular: false,
    description: 'Fresh Atlantic salmon cubes marinated in ponzu, served over sushi rice with sliced avocado and edamame.',
  },
  {
    id: 'dish-6',
    name: 'Pomodoro Pasta',
    category: 'Lunch',
    price: 88.0,
    weight: '300 g',
    calories: '490 kcal',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=800',
    popular: false,
    description: 'Artisanal penne tossed in San Marzano tomato sauce, fresh basil leaves, and Parmigiano Reggiano.',
  },
];

export const INITIAL_TABLES: Table[] = [
  { id: 't-1', number: '01', seats: 2, section: 'Main Hall', status: 'occupied', currentOrderTotal: 176.0, guestCount: 2 },
  { id: 't-2', number: '02', seats: 4, section: 'Main Hall', status: 'available' },
  { id: 't-3', number: '03', seats: 4, section: 'Main Hall', status: 'occupied', currentOrderTotal: 264.0, guestCount: 4 },
  { id: 't-4', number: '04', seats: 6, section: 'Main Hall', status: 'reserved' },
  { id: 't-5', number: '05', seats: 2, section: 'Terrace', status: 'available' },
  { id: 't-6', number: '06', seats: 4, section: 'Terrace', status: 'occupied', currentOrderTotal: 88.0, guestCount: 3 },
  { id: 't-7', number: '07', seats: 8, section: 'VIP Lounge', status: 'reserved' },
  { id: 't-8', number: '08', seats: 2, section: 'VIP Lounge', status: 'available' },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNo: '#FP-1024',
    businessType: 'restaurant',
    tableNumber: '01',
    items: [
      { dishName: 'Sunrise Mediterranean Bowl', quantity: 1, price: 88.0 },
      { dishName: 'Fresh Salad with pine nuts', quantity: 1, price: 88.0 },
    ],
    subtotal: 176.0,
    tax: 17.6,
    total: 193.6,
    status: 'Ready',
    timestamp: '12 mins ago',
    customerName: 'Table 01',
    waiterName: 'Jessica Harrison',
    paymentMethod: 'GCash',
  },
  {
    id: 'ord-102',
    orderNo: '#MP-8801',
    businessType: 'retail',
    items: [
      { dishName: 'Thin Sliced Pork Samgyupsal', quantity: 3, price: 88.0 },
      { dishName: 'USDA Choice Beef Samgyup Slices', quantity: 2, price: 88.0 },
    ],
    subtotal: 440.0,
    tax: 44.0,
    total: 484.0,
    status: 'Paid',
    timestamp: '18 mins ago',
    customerName: 'Walk-in Retail',
    waiterName: 'Jessica Harrison',
    paymentMethod: 'Cash',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'b-1',
    customerName: 'David Miller',
    time: '13:30',
    date: 'Today',
    guests: 4,
    tableNumber: '04',
    phone: '+63 917 123 4567',
    status: 'Confirmed',
  },
  {
    id: 'b-2',
    customerName: 'Sophia Laurent',
    time: '19:00',
    date: 'Today',
    guests: 6,
    tableNumber: '07',
    phone: '+63 918 987 6543',
    status: 'Confirmed',
  },
];
